server: Karion
servers:
  - 'null'
  - 'null'
  - '399@#@&a&lKarion@#@&6Freebuild/PvP Server.'
  - 'null'
  - '398@#@&a&lInsomnia@#@&6Spiele/Event und Parkour Server.'
  - 'null'
  - '54@#@&a&lAlassra@#@&6SkyBlock und Kreativ Server.'
  - 'null'
  - 'null'